# NETLIFY CONFIGURATION - PRILABSA WEBSITE 2025
# Security headers, redirects, and build configuration

[build]
  publish = "dist"
  command = "npm run test:run && npm run lint && npm run build"
  
# Build optimization flags
[build.environment]
  NODE_VERSION = "20.19.2"
  GENERATE_SOURCEMAP = "false"
  CI = "true"
  NPM_FLAGS = "--silent"

# Security Headers Implementation
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy (CSP) - Previene XSS y otras injecciones
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https: blob:;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://api.prilabsa.com;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
    '''
    
    # Security Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # HSTS (HTTP Strict Transport Security)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Cache Control para assets estáticos
    Cache-Control = "public, max-age=31536000, immutable"

# Cache específico para HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache para assets con hash
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects para SEO
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Fallback para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/v1/deploy-status"
  to = "/.netlify/functions/deploy-status"
  status = 200

[context.production]
  command = "npm run test:run && npm run lint && npm run build"

[context.deploy-preview]
  command = "npm run test:run && npm run lint && npm run build"

[context.branch-deploy]
  command = "npm run test:run && npm run lint && npm run build"
